### ISSUE TITLE
Levenshtein==0.12.0 is insecure (and yanked on pip)

### ISSUE THREAD

**Issue by hemmond** [jfjlaros/barcode#2]
**Describe the bug**
This package relies on `python-Levenshtein` package in version 0.12.0 and this version have a high severity vulnerability (see: [https://snyk.io/vuln/pip:python-Levenshtein](https://snyk.io/vuln/pip:python-Levenshtein)). This version is therefore "yanked" from PIP repositories.

**To Reproduce**
Steps to reproduce the behaviour:

1. On fresh system install this package via pip. 
2. See the warnings in terminal. 

**Expected behavior**
I expect that this package uses non-yanked version as its dependency.

**Screenshots**
No screenshot, only report from pip install.
```
WARNING: The candidate selected for download or install is a yanked version: 'python-levenshtein' candidate (version 0.12.0 at https://files.pythonhosted.org/packages/42/a9/d1785c85ebf9b7dfacd08938dd028209c34a0ea3b1bcdb895208bd40a67d/p
ython-Levenshtein-0.12.0.tar.gz#sha256=033a11de5e3d19ea25c9302d11224e1a1898fe5abd23c61c7c360c25195e3eb1 (from https://pypi.org/simple/python-levenshtein/))
Reason for being yanked: Insecure, upgrade to 0.12.1
```

**Desktop (please complete the following information):**
 - OS: Windows 10, using PyCharm embedded terminal. 
 - Version barcode==1.0.1

**Comment by jfjlaros** [comment]
Thank you for bringing this to my attention. I just released a new version that fixes this issue.
