### ISSUE TITLE
not barcodes after passing arguments

### ISSUE THREAD

**Issue by PhilippFW** [jfjlaros/barcode#3]
Hi,

for me

`barcode make barcode.txt works`

however when passing arguments like -d or other it only returns an empty file

bug?

**Comment by jfjlaros** [comment]
Can you share the exact command in order for me to reproduce the issue?

**Comment by PhilippFW** [comment]
Hi,

I used the excact code provided in readthedocs:

`barcode make -d 5 -l 10 -s 1 barcodes.txt
`

**Comment by jfjlaros** [comment]
Can you try again with the latest version (1.0.3)?

**Comment by PhilippFW** [comment]
works! thx
